name: Testing stuff

on:
  push:
    branches:
      - testing

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - name: commit messages joined
        env:
          COMMIT_MESSAGES_JOINED: ${{ join(toJson(github.event.commits.*.message)) }}
        run: echo "$COMMIT_MESSAGES_JOINED"
      - name: commit messages joined contains
        env:
          CONTAINS_SKIP: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
        run: echo "$CONTAINS_SKIP"
      - name: simple echo
        run: echo "echo!"
